-- V1: 초기 스키마 생성
-- Co-Talk 메시징 플랫폼의 모든 테이블을 정의한다.
-- ID는 애플리케이션에서 Snowflake ID로 생성하므로 SERIAL/GENERATED를 사용하지 않는다.
-- (예외: message_reactions, password_reset_tokens, terms_agreements, profile_history, hidden_friends는 GenerationType.IDENTITY 사용)

-- ============================================================
-- 1. users (참조되는 기본 테이블)
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT       NOT NULL PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255),
    nickname        VARCHAR(255) NOT NULL,
    avatar_url      VARCHAR(255),
    oauth_provider  VARCHAR(255),
    oauth_id        VARCHAR(255),
    status          VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
    role            VARCHAR(255) NOT NULL DEFAULT 'USER',
    online_status   VARCHAR(255) NOT NULL DEFAULT 'OFFLINE',
    last_active_at  TIMESTAMP,
    status_message  VARCHAR(60),
    background_url  VARCHAR(500),
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL
);

-- ============================================================
-- 2. chat_rooms
-- ============================================================
CREATE TABLE IF NOT EXISTS chat_rooms (
    id              BIGINT       NOT NULL PRIMARY KEY,
    name            VARCHAR(255),
    announcement    VARCHAR(500),
    type            VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL
);

-- ============================================================
-- 3. chat_room_members (FK -> chat_rooms, users)
-- ============================================================
CREATE TABLE IF NOT EXISTS chat_room_members (
    id                      BIGINT       NOT NULL PRIMARY KEY,
    chat_room_id            BIGINT       NOT NULL,
    user_id                 BIGINT       NOT NULL,
    role                    VARCHAR(255) NOT NULL DEFAULT 'MEMBER',
    last_read_at            TIMESTAMP,
    last_read_message_id    BIGINT,
    joined_at               TIMESTAMP    NOT NULL,
    updated_at              TIMESTAMP    NOT NULL,
    CONSTRAINT uk_chat_room_members_room_user UNIQUE (chat_room_id, user_id),
    CONSTRAINT fk_chat_room_members_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id),
    CONSTRAINT fk_chat_room_members_user      FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ============================================================
-- 4. messages (FK -> chat_rooms, users)
-- ============================================================
CREATE TABLE IF NOT EXISTS messages (
    id                          BIGINT         NOT NULL PRIMARY KEY,
    chat_room_id                BIGINT         NOT NULL,
    sender_id                   BIGINT         NOT NULL,
    content                     VARCHAR(4000)  NOT NULL,
    type                        VARCHAR(255)   NOT NULL DEFAULT 'TEXT',
    file_url                    VARCHAR(255),
    file_name                   VARCHAR(255),
    file_size                   BIGINT,
    file_content_type           VARCHAR(255),
    thumbnail_url               VARCHAR(255),
    reply_to_message_id         BIGINT,
    forwarded_from_message_id   BIGINT,
    link_preview_url            VARCHAR(2048),
    link_preview_title          VARCHAR(512),
    link_preview_description    VARCHAR(1000),
    link_preview_image_url      VARCHAR(2048),
    deleted_at                  TIMESTAMP,
    is_deleted                  BOOLEAN        NOT NULL DEFAULT false,
    created_at                  TIMESTAMP      NOT NULL,
    updated_at                  TIMESTAMP      NOT NULL,
    CONSTRAINT fk_messages_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id),
    CONSTRAINT fk_messages_sender    FOREIGN KEY (sender_id) REFERENCES users(id)
);

-- ============================================================
-- 5. message_reactions (IDENTITY PK, FK -> messages, users)
-- ============================================================
CREATE TABLE IF NOT EXISTS message_reactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    emoji       VARCHAR(50)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uk_message_reactions_msg_user_emoji UNIQUE (message_id, user_id, emoji),
    CONSTRAINT fk_message_reactions_message FOREIGN KEY (message_id) REFERENCES messages(id),
    CONSTRAINT fk_message_reactions_user    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ============================================================
-- 6. friends (FK -> users)
-- ============================================================
CREATE TABLE IF NOT EXISTS friends (
    id          BIGINT       NOT NULL PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    friend_id   BIGINT       NOT NULL,
    status      VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uk_friends_user_friend UNIQUE (user_id, friend_id),
    CONSTRAINT fk_friends_user   FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_friends_friend FOREIGN KEY (friend_id) REFERENCES users(id)
);

-- ============================================================
-- 7. friend_requests (FK -> users)
-- ============================================================
CREATE TABLE IF NOT EXISTS friend_requests (
    id              BIGINT       NOT NULL PRIMARY KEY,
    requester_id    BIGINT       NOT NULL,
    receiver_id     BIGINT       NOT NULL,
    status          VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    CONSTRAINT uk_friend_request_requester_receiver UNIQUE (requester_id, receiver_id),
    CONSTRAINT fk_friend_requests_requester FOREIGN KEY (requester_id) REFERENCES users(id),
    CONSTRAINT fk_friend_requests_receiver  FOREIGN KEY (receiver_id) REFERENCES users(id)
);

-- ============================================================
-- 8. blocks (FK -> users)
-- ============================================================
CREATE TABLE IF NOT EXISTS blocks (
    id          BIGINT       NOT NULL PRIMARY KEY,
    blocker_id  BIGINT       NOT NULL,
    blocked_id  BIGINT       NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uk_blocks_blocker_blocked UNIQUE (blocker_id, blocked_id),
    CONSTRAINT fk_blocks_blocker FOREIGN KEY (blocker_id) REFERENCES users(id),
    CONSTRAINT fk_blocks_blocked FOREIGN KEY (blocked_id) REFERENCES users(id)
);

-- ============================================================
-- 9. reports (FK -> users, messages, chat_rooms)
-- ============================================================
CREATE TABLE IF NOT EXISTS reports (
    id                      BIGINT         NOT NULL PRIMARY KEY,
    reporter_id             BIGINT         NOT NULL,
    reported_user_id        BIGINT,
    reported_message_id     BIGINT,
    reported_chat_room_id   BIGINT,
    type                    VARCHAR(255)   NOT NULL,
    reason                  VARCHAR(255)   NOT NULL,
    description             VARCHAR(1000),
    status                  VARCHAR(255)   NOT NULL DEFAULT 'PENDING',
    admin_note              VARCHAR(1000),
    processed_at            TIMESTAMP,
    processed_by            BIGINT,
    created_at              TIMESTAMP      NOT NULL,
    updated_at              TIMESTAMP      NOT NULL,
    CONSTRAINT fk_reports_reporter       FOREIGN KEY (reporter_id) REFERENCES users(id),
    CONSTRAINT fk_reports_reported_user  FOREIGN KEY (reported_user_id) REFERENCES users(id),
    CONSTRAINT fk_reports_reported_msg   FOREIGN KEY (reported_message_id) REFERENCES messages(id),
    CONSTRAINT fk_reports_reported_room  FOREIGN KEY (reported_chat_room_id) REFERENCES chat_rooms(id)
);

-- ============================================================
-- 10. device_tokens (FK -> users)
-- ============================================================
CREATE TABLE IF NOT EXISTS device_tokens (
    id              BIGINT       NOT NULL PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    token           VARCHAR(255) NOT NULL UNIQUE,
    device_type     VARCHAR(20)  NOT NULL,
    active          BOOLEAN      NOT NULL DEFAULT true,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    CONSTRAINT fk_device_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_device_token_user_id ON device_tokens(user_id);

-- ============================================================
-- 11. notification_settings (FK -> users)
-- ============================================================
CREATE TABLE IF NOT EXISTS notification_settings (
    id                              BIGINT       NOT NULL PRIMARY KEY,
    user_id                         BIGINT       NOT NULL UNIQUE,
    message_notification            BOOLEAN      NOT NULL DEFAULT true,
    friend_request_notification     BOOLEAN      NOT NULL DEFAULT true,
    group_invite_notification       BOOLEAN      NOT NULL DEFAULT true,
    sound_enabled                   BOOLEAN      NOT NULL DEFAULT true,
    vibration_enabled               BOOLEAN      NOT NULL DEFAULT true,
    do_not_disturb_enabled          BOOLEAN      NOT NULL DEFAULT false,
    do_not_disturb_start            VARCHAR(255),
    do_not_disturb_end              VARCHAR(255),
    created_at                      TIMESTAMP    NOT NULL,
    updated_at                      TIMESTAMP    NOT NULL,
    CONSTRAINT fk_notification_settings_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ============================================================
-- 12. password_reset_tokens (IDENTITY PK, FK -> users)
-- ============================================================
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255)  NOT NULL UNIQUE,
    user_id     BIGINT        NOT NULL,
    email       VARCHAR(255)  NOT NULL,
    expires_at  TIMESTAMP     NOT NULL,
    used_at     TIMESTAMP,
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ============================================================
-- 13. terms_agreements (IDENTITY PK, FK -> users)
-- ============================================================
CREATE TABLE IF NOT EXISTS terms_agreements (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    terms_type      VARCHAR(255) NOT NULL,
    terms_version   VARCHAR(255) NOT NULL,
    agreed          BOOLEAN      NOT NULL,
    agreed_at       TIMESTAMP,
    withdrawn_at    TIMESTAMP,
    ip_address      VARCHAR(255),
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    CONSTRAINT fk_terms_agreements_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ============================================================
-- 14. refresh_tokens (FK -> users)
-- ============================================================
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          BIGINT       NOT NULL PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    token       VARCHAR(255) NOT NULL UNIQUE,
    expires_at  TIMESTAMP    NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT false,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_refresh_token_user_id ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_token_token ON refresh_tokens(token);

-- ============================================================
-- 15. profile_history (IDENTITY PK, FK -> users)
-- ============================================================
CREATE TABLE IF NOT EXISTS profile_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    type        VARCHAR(20)  NOT NULL,
    url         VARCHAR(500),
    content     VARCHAR(60),
    is_private  BOOLEAN      NOT NULL DEFAULT false,
    is_current  BOOLEAN      NOT NULL DEFAULT false,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_profile_history_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_profile_history_user_type ON profile_history(user_id, type);

-- ============================================================
-- 16. hidden_friends (IDENTITY PK, FK -> users)
-- ============================================================
CREATE TABLE IF NOT EXISTS hidden_friends (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    friend_id   BIGINT       NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uk_hidden_friends_user_friend UNIQUE (user_id, friend_id),
    CONSTRAINT fk_hidden_friends_user   FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_hidden_friends_friend FOREIGN KEY (friend_id) REFERENCES users(id)
);
