apiVersion: v1
kind: ServiceAccount
metadata:
  name: cotalk-sa
  namespace: cotalk
  labels:
    app.kubernetes.io/name: cotalk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cotalk-role
  namespace: cotalk
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cotalk-rolebinding
  namespace: cotalk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cotalk-role
subjects:
  - kind: ServiceAccount
    name: cotalk-sa
    namespace: cotalk
