apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cotalk-dev

resources:
  - ../../base

nameSuffix: -dev

commonLabels:
  environment: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: cotalk-app
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
    target:
      kind: HorizontalPodAutoscaler
      name: cotalk-hpa

configMapGenerator:
  - name: cotalk-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=dev,kubernetes
      - LOGGING_LEVEL_COM_COTALK=DEBUG
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0

images:
  - name: cotalk-app
    newTag: dev-latest
